# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

min_var_eigen <- function(x_, a_, N = 100L, eps = 1e-6) {
    .Call(`_migou_min_var_eigen`, x_, a_, N, eps)
}

weighted_Kinship_w <- function(p_A, mu, w, snps, chunk) {
    .Call(`_migou_weighted_Kinship_w`, p_A, mu, w, snps, chunk)
}

